apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  timeout: 15m
  chart:
    spec:
      version: ">=9.0.0 <10.0.0"
  values:
    livenessProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 25
      failureThreshold: 90
      successThreshold: 1
    readinessProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
    startupProbe:
      enabled: false
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 25
      failureThreshold: 90
      successThreshold: 1
    resources:
      limits:
        memory: 1024Mi
        cpu: 1024m
      requests:
        cpu: 512m
        memory: 512Mi
    replicaCount: 2
    httpRoute:
      enabled: true
      hostnames:
        - files.pipenberg.eu
      parentRefs:
      - name: infra-gateway
        sectionName: websecure
        namespace: traefik
    phpClientHttpsFix:
      enabled: true
      protocol: https
    nextcloud:
      host: files.pipenberg.eu
      trustedDomains:
        - nextcloud.kube.home
        - files.pipenberg.eu
      existingSecret: 
        enabled: true
        secretName: nextcloud-credentials
        usernameKey: nextcloud-username
        passwordKey: nextcloud-password
      # Permissions fix from: https://github.com/nextcloud/helm/issues/187#issuecomment-2674561977
      extraInitContainers:
        - name: create-redis-session-ini
          image: docker.io/busybox:1.36-uclibc
          command:
            - sh
            - -c
            - touch /mnt/redis-session.ini
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: php-confd
              mountPath: /mnt
      extraVolumeMounts:
        - name: php-confd
          mountPath: /usr/local/etc/php/conf.d/redis-session.ini
          subPath: redis-session.ini
      extraVolumes:
        - name: php-confd
          emptyDir:
            sizeLimit: 1Gi
      podSecurityContext:
        fsGroup: 33 # Without fsGroup=33 Nextcloud will crash, since it requires the data directory to be owned by the www-data user.
        runAsGroup: 33 # www-data
        runAsNonRoot: true
        runAsUser: 33 # www-data
        seccompProfile:
          type: RuntimeDefault
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      # end of permissions fix
      mariaDbInitContainer:
        securityContext:
          runAsUser: 33
          runAsGroup: 33
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
    persistence:
        enabled: true
        accessMode: ReadWriteMany
        size: 8Gi
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: mariadb
      existingSecret:
        enabled: true
        secretName: "mariadb-credentials"
        usernameKey: mariadb-username
        passwordKey: mariadb-password
        hostKey: mariadb-database-host
        databaseKey: mariadb-database
    externalRedis:
      enabled: true
      host: "cache.pipenberg.eu"
      port: "6379"
      existingSecret:
        enabled: true
        secretName: "redis-credentials"
        passwordKey: redis-password
    #mariadb:
    #  enabled: false
    #  auth:
    #    existingSecret: "mariadb-credentials"
    #    database: nextcloud
    #  primary:
    #    persistence:
    #      enabled: true
    #  mariaDbInitContainer:
    #    resources:
    #      limits:
    #        memory: 128Mi
    #        cpu: 100m
    #      requests:
    #        cpu: 100m
    #        memory: 128Mi
    #redis:
    #  auth:
    #    enabled: true
    #    existingSecret: "redis-credentials"
    #    existingSecretPasswordKey: "redis-password"
    #  enabled: true
    #  master:
    #    persistence:
    #      enabled: true
    #  replica:
    #    persistence:
    #      enabled: true
