apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
timeout: 15m
spec:
  chart:
    spec:
      version: ">=9.0.0 <10.0.0"
  values:
    resources:
      limits:
       memory: 128Mi
      requests:
       cpu: 100m
       memory: 128Mi
    replicaCount: 1
    httpRoute:
      enabled: true
      hostnames:
        - files.pipenberg.eu
      parentRefs:
      - name: infra-gateway
        sectionName: websecure
        namespace: traefik
    phpClientHttpsFix:
      enabled: true
      protocol: https
    nextcloud:
      host: nextcloud.kube.home
      trustedDomains:
        - nextcloud.kube.home
        - files.pipenberg.eu
      existingSecret: 
        enabled: true
        secretName: nextcloud-credentials
        usernameKey: nextcloud-username
        passwordKey: nextcloud-password
    persistence:
        enabled: true
        nextcloudData:
          enabled: true
          accessMode: ReadWriteOnce
          size: 8Gi
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: mariadb
      existingSecret:
        enabled: true
        secretName: "mariadb-credentials"
        usernameKey: mariadb-username
        passwordKey: mariadb-password
    externalRedis:
      enabled: true
      existingSecret:
        enabled: true
        secretName: "redis-credentials"
        passwordKey: redis-password
    mariadb:
      enabled: true
      auth:
        existingSecret: "mariadb-credentials"
        database: nextcloud
      primary:
        persistence:
          enabled: true
      mariaDbInitContainer:
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
    redis:
      auth:
        enabled: true
        existingSecret: "redis-credentials"
        existingSecretPasswordKey: "redis-password"
      enabled: true
      master:
        persistence:
          enabled: true
