apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  chart:
    spec:
      version: ">=9.0.0"
  values:
    replicaCount: 1
    httpRoute:
      enabled: true
      hostnames:
        - files.pipenberg.eu
      parentRefs:
      - name: infra-gateway
        sectionName: websecure
        namespace: traefik
    nextcloud:
      trustedDomains:
        - localhost
        - nextcloud.kube.home
        - files.pipenberg.eu
    persistence:
      enabled: true
    internalDatabase:
      enabled: false
    mariadb:
      enabled: true
      primary:
        persistence:
          enabled: true
    redis:
      enabled: true
