---
apiVersion: v1
stringData:
    nextcloud-username: ENC[AES256_GCM,data:HjbBcsItlug=,iv:A0qm27erriV1JcJjBNxqCjAXZ0Esi1KjsNPOHlEzIic=,tag:fn+xLKKkXiW504GaN0c2nA==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:eTvY/tXC34uXAOGQ,iv:KBFLTohdHqCSVEDHKzWcmEcjyZs5GiyPuj1oaUrmyrI=,tag:k/6lLvPUyM9ej2ZtwY/Ipw==,type:str]
kind: Secret
metadata:
    name: nextcloud-credentials
    namespace: nextcloud
type: Opaque
sops:
    age:
        - recipient: age1cp7gh5ex4nnjf7q3mx40mu0p8d0eyhsv8d4eap8tymxvax65mp0s72e9ye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZ2hJN2R4MURmK3ZhczJk
            S2ZFNzR6NmVBb3RmeDE0Yzcvdk5tMDhON0NjClBtcnpUek5FWnYwemFYTFhCUjJL
            MlhrUUsxNDRYNzliYUJRUHVmVUJPSEUKLS0tIEt6bm1oNDN3Nld2dWxwK2ZDYTNm
            N3ZjVEpscjlrd1NJOUxrbFVmTDVaWEEKStKbcKpWNGS1Q3c79yKoDNSbaCj0iA9i
            g65ESAMPckPPSaBqXVvEKMMeBzdo5zJxdX2NrR1K87uKngSg4Oybug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T11:04:25Z"
    mac: ENC[AES256_GCM,data:TdHRdbEDQiRLZfWt3vGI/hh/K84hwZoQ4Z9b6WTQo0D7MddklNZ20CwoiRIOsLcz42n2Ya/nRkQjJx2FLtsPock+sYOOD+YcFoaGTh/ovCdx7tiC4dCfX7t0UOwudF3i1SbgJQ+UHm0KpWoHhVxxyIDD0+ye0UBz2BoYep6pUew=,iv:zqCyYdyrs1VDvjBtg626lCdj7QHgXS2cOxHQWWWWhos=,tag:PmTeRXLJ2Pvjaqx21GUcqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
stringData:
    mariadb-username: ENC[AES256_GCM,data:MWAbM3xvXB0h,iv:7wfe1uJaf2lLPq+hDUgj3Wytqh+bKBPlBLCqltrl484=,tag:uqgU9NJZSvqxjHU1ubarnQ==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:R/D1gp+irkQVVfr1,iv:Vr8wYqQxhFhw2lBHFlPFQQaaUkC9dBp43jsdgaDNXjk=,tag:mw+9PXxWugC57OpW5hG3Pw==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:fpOF7ryeYUqFBKG8,iv:gMMGTV7ac9+r+2lpY6VGXlVgyApHSVueb3X7QLa8EmE=,tag:HzPpLqM86HPBwTCJ3MXjmA==,type:str]
    mariadb-password: ENC[AES256_GCM,data:pltkMzMUa3O2l4RQ,iv:LwhRA1CKGWVM0TpeY+TNYNNFXmsvPQXhujHQ9NgUwaw=,tag:Np20o6XV8yW39sjE0leCJA==,type:str]
    mariadb-database-host: ENC[AES256_GCM,data:JJghf1hqqpzTSpRLcBdN,iv:GarPPPuC8odOSNLB58Is+dkYEOg/nCEnHg1WAZKebvk=,tag:O337KaCmZLEZsjTSAN9Zcw==,type:str]
    mariadb-database: ENC[AES256_GCM,data:LZ6zmrAUD+Ev,iv:ah9UXPY0Qo9k1y6Es+9vgvWrkOqqw5sUjJq/oBZdAzc=,tag:Kx/0L8ZbtlejyqJKyvKf1A==,type:str]
kind: Secret
metadata:
    name: mariadb-credentials
    namespace: nextcloud
type: Opaque
sops:
    age:
        - recipient: age1cp7gh5ex4nnjf7q3mx40mu0p8d0eyhsv8d4eap8tymxvax65mp0s72e9ye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZm1ZS05GcGY2eU5IZEtl
            bUVRaytKZEZ0dTVYcnBMRDZWL2JuQnorM1hzCmx2cXFjOTJ0MC9xTHRqR0Vld1Jm
            MklVOUlRcEtiMU1sNUpZQlpLemxQY3cKLS0tIG5XTUZOV1VJbWRaYm9KUmRBKzFV
            VXlCaXNNY1g0bkNITm1meHltaE4xbnMK00GvorndmaIwx2wz/XdRPg1WulrPhzm+
            IUX4iw+TgJjFqiPJTY4ik14jNiZg2GvinHCZERyWM4U2l8BXup8Izw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T14:03:00Z"
    mac: ENC[AES256_GCM,data:HvXIdGqCwSZrymzDK7SUzhRB7WwmsB2jf2w+62XoN+xhP17Bi8I4xyLqGrWJyWdyD+MHjDLi/DvIm2HfPRbtNE6XBYEV6NcYB9+foIidrUV0o7WN5Z16m/6aStQ53LxCOKCKq7PzrvcH4u7/T9tMToBkrHBTqMJDizRBBaXjydQ=,iv:8iReLDLf7Xh0ToUekZ18Q+u89CcmK2wvDElVbjtsH1M=,tag:0gf/8Z3oDg8tGdwd/7S5zw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
stringData:
    redis-password: ENC[AES256_GCM,data:R3M5t/sPCFB8kI2N,iv:4yKVz3XZ0IQEJK4ZG15d7bIFVdImd6bIjAjKZbLiRw8=,tag:2smTU3iGy/j3gUR+5dIbmQ==,type:str]
kind: Secret
metadata:
    name: redis-credentials
    namespace: nextcloud
type: Opaque
sops:
    age:
        - recipient: age1cp7gh5ex4nnjf7q3mx40mu0p8d0eyhsv8d4eap8tymxvax65mp0s72e9ye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZ2hJN2R4MURmK3ZhczJk
            S2ZFNzR6NmVBb3RmeDE0Yzcvdk5tMDhON0NjClBtcnpUek5FWnYwemFYTFhCUjJL
            MlhrUUsxNDRYNzliYUJRUHVmVUJPSEUKLS0tIEt6bm1oNDN3Nld2dWxwK2ZDYTNm
            N3ZjVEpscjlrd1NJOUxrbFVmTDVaWEEKStKbcKpWNGS1Q3c79yKoDNSbaCj0iA9i
            g65ESAMPckPPSaBqXVvEKMMeBzdo5zJxdX2NrR1K87uKngSg4Oybug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T11:04:25Z"
    mac: ENC[AES256_GCM,data:TdHRdbEDQiRLZfWt3vGI/hh/K84hwZoQ4Z9b6WTQo0D7MddklNZ20CwoiRIOsLcz42n2Ya/nRkQjJx2FLtsPock+sYOOD+YcFoaGTh/ovCdx7tiC4dCfX7t0UOwudF3i1SbgJQ+UHm0KpWoHhVxxyIDD0+ye0UBz2BoYep6pUew=,iv:zqCyYdyrs1VDvjBtg626lCdj7QHgXS2cOxHQWWWWhos=,tag:PmTeRXLJ2Pvjaqx21GUcqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
