apiVersion: v1
stringData:
    nextcloud-username: ENC[AES256_GCM,data:HjbBcsItlug=,iv:A0qm27erriV1JcJjBNxqCjAXZ0Esi1KjsNPOHlEzIic=,tag:fn+xLKKkXiW504GaN0c2nA==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:eTvY/tXC34uXAOGQ,iv:KBFLTohdHqCSVEDHKzWcmEcjyZs5GiyPuj1oaUrmyrI=,tag:k/6lLvPUyM9ej2ZtwY/Ipw==,type:str]
kind: Secret
metadata:
    name: nextcloud-credentials
    namespace: nextcloud
type: Opaque
sops:
    age:
        - recipient: age1cp7gh5ex4nnjf7q3mx40mu0p8d0eyhsv8d4eap8tymxvax65mp0s72e9ye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZ2hJN2R4MURmK3ZhczJk
            S2ZFNzR6NmVBb3RmeDE0Yzcvdk5tMDhON0NjClBtcnpUek5FWnYwemFYTFhCUjJL
            MlhrUUsxNDRYNzliYUJRUHVmVUJPSEUKLS0tIEt6bm1oNDN3Nld2dWxwK2ZDYTNm
            N3ZjVEpscjlrd1NJOUxrbFVmTDVaWEEKStKbcKpWNGS1Q3c79yKoDNSbaCj0iA9i
            g65ESAMPckPPSaBqXVvEKMMeBzdo5zJxdX2NrR1K87uKngSg4Oybug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T11:04:25Z"
    mac: ENC[AES256_GCM,data:TdHRdbEDQiRLZfWt3vGI/hh/K84hwZoQ4Z9b6WTQo0D7MddklNZ20CwoiRIOsLcz42n2Ya/nRkQjJx2FLtsPock+sYOOD+YcFoaGTh/ovCdx7tiC4dCfX7t0UOwudF3i1SbgJQ+UHm0KpWoHhVxxyIDD0+ye0UBz2BoYep6pUew=,iv:zqCyYdyrs1VDvjBtg626lCdj7QHgXS2cOxHQWWWWhos=,tag:PmTeRXLJ2Pvjaqx21GUcqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:Xm5zQuqcSIXDDWlW,iv:vWxKyB3LCtK3DmhK8upgtIwgPDFsfGzcy4IdLYG3gic=,tag:sStj5Pd1Iq/GkyCNRT2acA==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:dieozSnCOMQpIidt,iv:jQ4v0BQ+mzWuuWQElhSgKWt5RAWF5LN9yzYPKqf3dIw=,tag:lA/Drm10+7rHl2Zs3mUSYw==,type:str]
    mariadb-password: ENC[AES256_GCM,data:qATDtpLtMcKbAZY4,iv:se1R3WgS025nICXnxkwGMT5cLt/ldaZnVS08qEg4LPs=,tag:+uIzSOGJoLsav9ffBFP8bw==,type:str]
kind: Secret
metadata:
    name: mariadb-credentials
    namespace: nextcloud
type: Opaque
sops:
    age:
        - recipient: age1cp7gh5ex4nnjf7q3mx40mu0p8d0eyhsv8d4eap8tymxvax65mp0s72e9ye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZ2hJN2R4MURmK3ZhczJk
            S2ZFNzR6NmVBb3RmeDE0Yzcvdk5tMDhON0NjClBtcnpUek5FWnYwemFYTFhCUjJL
            MlhrUUsxNDRYNzliYUJRUHVmVUJPSEUKLS0tIEt6bm1oNDN3Nld2dWxwK2ZDYTNm
            N3ZjVEpscjlrd1NJOUxrbFVmTDVaWEEKStKbcKpWNGS1Q3c79yKoDNSbaCj0iA9i
            g65ESAMPckPPSaBqXVvEKMMeBzdo5zJxdX2NrR1K87uKngSg4Oybug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T11:04:25Z"
    mac: ENC[AES256_GCM,data:TdHRdbEDQiRLZfWt3vGI/hh/K84hwZoQ4Z9b6WTQo0D7MddklNZ20CwoiRIOsLcz42n2Ya/nRkQjJx2FLtsPock+sYOOD+YcFoaGTh/ovCdx7tiC4dCfX7t0UOwudF3i1SbgJQ+UHm0KpWoHhVxxyIDD0+ye0UBz2BoYep6pUew=,iv:zqCyYdyrs1VDvjBtg626lCdj7QHgXS2cOxHQWWWWhos=,tag:PmTeRXLJ2Pvjaqx21GUcqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
stringData:
    redis-password: ENC[AES256_GCM,data:R3M5t/sPCFB8kI2N,iv:4yKVz3XZ0IQEJK4ZG15d7bIFVdImd6bIjAjKZbLiRw8=,tag:2smTU3iGy/j3gUR+5dIbmQ==,type:str]
kind: Secret
metadata:
    name: redis-credentials
    namespace: nextcloud
type: Opaque
sops:
    age:
        - recipient: age1cp7gh5ex4nnjf7q3mx40mu0p8d0eyhsv8d4eap8tymxvax65mp0s72e9ye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZ2hJN2R4MURmK3ZhczJk
            S2ZFNzR6NmVBb3RmeDE0Yzcvdk5tMDhON0NjClBtcnpUek5FWnYwemFYTFhCUjJL
            MlhrUUsxNDRYNzliYUJRUHVmVUJPSEUKLS0tIEt6bm1oNDN3Nld2dWxwK2ZDYTNm
            N3ZjVEpscjlrd1NJOUxrbFVmTDVaWEEKStKbcKpWNGS1Q3c79yKoDNSbaCj0iA9i
            g65ESAMPckPPSaBqXVvEKMMeBzdo5zJxdX2NrR1K87uKngSg4Oybug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T11:04:25Z"
    mac: ENC[AES256_GCM,data:TdHRdbEDQiRLZfWt3vGI/hh/K84hwZoQ4Z9b6WTQo0D7MddklNZ20CwoiRIOsLcz42n2Ya/nRkQjJx2FLtsPock+sYOOD+YcFoaGTh/ovCdx7tiC4dCfX7t0UOwudF3i1SbgJQ+UHm0KpWoHhVxxyIDD0+ye0UBz2BoYep6pUew=,iv:zqCyYdyrs1VDvjBtg626lCdj7QHgXS2cOxHQWWWWhos=,tag:PmTeRXLJ2Pvjaqx21GUcqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
