apiVersion: v1
stringData:
    nextcloud-username: ENC[AES256_GCM,data:2LBQcrf5v3k=,iv:XeJhNEXxv42ba+PKHKP25wIVirHIDS8gcxcfDb6kkkA=,tag:Z1JXGUtl7oRna+9DpNySoQ==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:E1LgWE7UtSdRkYvS,iv:+E4MAP1cvVglMzdC469Y71MdM1WP95mKJVwnYDQkC30=,tag:0Xr02MSDyfwaz8kfqS7YzQ==,type:str]
kind: Secret
metadata:
    name: nextcloud-credentials
    namespace: nextcloud
type: Opaque
sops:
    age:
        - recipient: age14x7z7kqzkfhk7q3hx9ny86zjp52q5jn36n3jfxeavd34xjxl9smsk0xxu7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaWtESDdEVWZwb1JlODVr
            cWtYQ3RPQWtoOEtqVCtJa09Qc1dsWDFORVRVCjJabDFLaGZlcFN2YThWMU5ZeC85
            dGhKY3BkaUswc1FXWWpDQVR5cWxMaWcKLS0tIFdVU0hBRnIrY2hUYXdZU1JlNG5P
            KzdkUUNoSWYyYlBIRGZla2VlVmRNSFEKnER/K7DK7Yx71nASph2Dn+KWNViNzuOU
            QVnOnknCORU7l1IB6ItX3uUuS6zakJVkZ6StO5MMGcXtl9EvrN0VtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T09:25:32Z"
    mac: ENC[AES256_GCM,data:4rMlF6YZdlN9+oASFCpg575D7Nfehfuw+0wgRUoFAvTSH6bUs6ydQFOvHRwECnkt7r3OvPNc6ulFfYEcSYImqzPckO4sX3ycRN1MH1tEEW1pBVQi+2uayoo5Uk1erXmS0JG1z+/xOKzn2Dw7xv4iDoUEAs5dzg9DV0WKBKSAr3E=,iv:zvYPDnadcxckJsdtwmvG9rBQNI4V806aA+AurVXMDZs=,tag:Z+HntAl8QJI/j7mu8ceniw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:WqBpUrfzo9boRfUm,iv:Px/fiZQl89+M2f2tux4nfU+kTn5t1rZF6xwgIO54zpA=,tag:S7z1az8WS7Lm/eppcLdAGQ==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:/lfXK4w+I26CK1YD,iv:FQ28zyCj8UIJr9Ll9QNvNlH1u5NlB8hesI3TH4FPPto=,tag:mbcvsYEcnk6N803m0Bau9g==,type:str]
    mariadb-password: ENC[AES256_GCM,data:/2LQ18k3/aplAOoz,iv:Hg3GLIzBhYpHycc8lc7cHjxVFlc65OGs5JofnGL5FRE=,tag:3OQ4KQ0xt8K4crf+tRRY2A==,type:str]
kind: Secret
metadata:
    name: mariadb-credentials
    namespace: nextcloud
type: Opaque
sops:
    age:
        - recipient: age14x7z7kqzkfhk7q3hx9ny86zjp52q5jn36n3jfxeavd34xjxl9smsk0xxu7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaWtESDdEVWZwb1JlODVr
            cWtYQ3RPQWtoOEtqVCtJa09Qc1dsWDFORVRVCjJabDFLaGZlcFN2YThWMU5ZeC85
            dGhKY3BkaUswc1FXWWpDQVR5cWxMaWcKLS0tIFdVU0hBRnIrY2hUYXdZU1JlNG5P
            KzdkUUNoSWYyYlBIRGZla2VlVmRNSFEKnER/K7DK7Yx71nASph2Dn+KWNViNzuOU
            QVnOnknCORU7l1IB6ItX3uUuS6zakJVkZ6StO5MMGcXtl9EvrN0VtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T09:25:32Z"
    mac: ENC[AES256_GCM,data:4rMlF6YZdlN9+oASFCpg575D7Nfehfuw+0wgRUoFAvTSH6bUs6ydQFOvHRwECnkt7r3OvPNc6ulFfYEcSYImqzPckO4sX3ycRN1MH1tEEW1pBVQi+2uayoo5Uk1erXmS0JG1z+/xOKzn2Dw7xv4iDoUEAs5dzg9DV0WKBKSAr3E=,iv:zvYPDnadcxckJsdtwmvG9rBQNI4V806aA+AurVXMDZs=,tag:Z+HntAl8QJI/j7mu8ceniw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
stringData:
    redis-password: ENC[AES256_GCM,data:Z5WpaSyjQcYFczQh,iv:8m1s1RbpC+Rww77moIq5xRCb4N/wn+TmZrTBMICwxMk=,tag:+EzozE42dm4W3X24Lw3coQ==,type:str]
kind: Secret
metadata:
    name: redis-credentials
    namespace: nextcloud
type: Opaque
sops:
    age:
        - recipient: age14x7z7kqzkfhk7q3hx9ny86zjp52q5jn36n3jfxeavd34xjxl9smsk0xxu7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaWtESDdEVWZwb1JlODVr
            cWtYQ3RPQWtoOEtqVCtJa09Qc1dsWDFORVRVCjJabDFLaGZlcFN2YThWMU5ZeC85
            dGhKY3BkaUswc1FXWWpDQVR5cWxMaWcKLS0tIFdVU0hBRnIrY2hUYXdZU1JlNG5P
            KzdkUUNoSWYyYlBIRGZla2VlVmRNSFEKnER/K7DK7Yx71nASph2Dn+KWNViNzuOU
            QVnOnknCORU7l1IB6ItX3uUuS6zakJVkZ6StO5MMGcXtl9EvrN0VtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T09:25:32Z"
    mac: ENC[AES256_GCM,data:4rMlF6YZdlN9+oASFCpg575D7Nfehfuw+0wgRUoFAvTSH6bUs6ydQFOvHRwECnkt7r3OvPNc6ulFfYEcSYImqzPckO4sX3ycRN1MH1tEEW1pBVQi+2uayoo5Uk1erXmS0JG1z+/xOKzn2Dw7xv4iDoUEAs5dzg9DV0WKBKSAr3E=,iv:zvYPDnadcxckJsdtwmvG9rBQNI4V806aA+AurVXMDZs=,tag:Z+HntAl8QJI/j7mu8ceniw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
